### ISSUE TITLE
PlutoSliderServer on Windows

### ISSUE THREAD

**Issue by VivaldoMendes** [JuliaPluto/PlutoSliderServer.jl#102]
Hi,
I am trying to use PlutoSliderServer for the first time. I created a Julia environment that I called `plutoserver`, then I did `add PlutoSliderServer`. Apparently, the installation went smoothly. I tried the first example on the website, and I got the message:

```
julia> path_to_notebook = download("https://raw.githubusercontent.com/fonsp/Pluto.jl/v0.17.2/sample/Interactivity.jl")
"C:\\Users\\UTILIZ~1\\AppData\\Local\\Temp\\jl_49sv0d6TwR"

julia> PlutoSliderServer.run_notebook("C:\\Users\\UTILIZ~1\\AppData\\Local\\Temp\\jl_49sv0d6TwR")
ERROR: AssertionError: PlutoSliderServer does not work on Windows yet!

```
Is the error message correct, or am I doing something wrong?
Thanks

**Comment by VivaldoMendes** [comment]
Hi @fonsp, thanks for replying.

I have tested PlutoSliderServer on Linux (Ubuntu) as well. However, I kept doing something stupid. As far as I can understand, in Linux, the plutosliderserver seems to run OK and create the server, but then it spits out the following error:

```
error: Uncaught PermissionDenied: Permission denied (os error 13) about ["/tmp/systemd-private-ef8b2c2d7f1f40388db3325afb12e1dc-systemd-timesyncd.service-sNRh7g"]
    const watcher = Deno.watchFs("/tmp");
                         ^
    at new FsWatcher (deno:runtime/js/40_fs_events.js:19:23)
    at Object.watchFs (deno:runtime/js/40_fs_events.js:64:12)
    at file:///home/violeta/$deno$eval.js:1:26
```
I would be more than glad to help, but I wonder if I can be of much help. I know some cases where PlutoSliderServer works very well, e.g., @jbrea 's course [here](https://bio322.epfl.ch/).

**Comment by jbrea** [comment]
If the sliderserver does not have write access to "/tmp" you could set the environment variable TEMP to some path it has write access to.

**Comment by fonsp** [comment]
@VivaldoMendes thanks for the report! Can you create a new issue and post your complete terminal log? Also post the output of:
```
# see permissions of the `/tmp` folder
ls -lha / | grep tmp
touch /tmp/asdf.txt
```

**Comment by VivaldoMendes** [comment]
Hi @fonsp  and @jbrea 
I did as you suggested and I had no problem to create the text file in the TEMP folder. The permissions are here:
```
violeta@violeta-QOSMIO-X70-B:~$ ls -lha / | grep tmp
drwxrwxrwt  19 root root  20K Mar 31 16:36 tmp
violeta@violeta-QOSMIO-X70-B:~$ touch /tmp/asdf.txt
```
Still not sure what is preventing the server to be reached.

Thanks

**Comment by mrufsvold** [comment]
I would love to take on Windows support, but could @fonsp point me to a starting point of where the URL <-> file path work is done? I started looking over the source code and couldn't find a starting point.
